import React, { useMemo, useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useStore, Sale } from '../../data/StoreContext';
import { COLORS, money } from '../../components/theme';

const FILTERS = ['Hoje', '7 dias', 'Tudo'];

function SaleRow({ sale }: { sale: Sale }) {
  const date = new Date(sale.date);
  return <View style={styles.saleCard}><View style={[styles.saleIcon, { backgroundColor: sale.itemType === 'SERVICE' ? '#FFF3E5' : COLORS.surfaceAlt }]}><Ionicons name={sale.itemType === 'SERVICE' ? 'construct-outline' : 'cart-outline'} size={19} color={sale.itemType === 'SERVICE' ? COLORS.orange : COLORS.accent} /></View><View style={styles.saleInfo}><View style={styles.saleTitleRow}><Text style={styles.saleName} numberOfLines={1}>Venda #{sale.number}</Text><Text style={styles.saleTotal}>{money(sale.totalCents)}</Text></View><Text style={styles.saleItem} numberOfLines={1}>{sale.quantity}x {sale.itemName}</Text><Text style={styles.saleMeta}>{date.toLocaleDateString('pt-BR')} às {date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })} · {sale.paymentMethod}{sale.customerName ? ` · ${sale.customerName}` : ''}</Text></View></View>;
}

export default function SalesScreen() {
  const { sales } = useStore();
  const [filter, setFilter] = useState('7 dias');
  const filtered = useMemo(() => { const now = Date.now(); return [...sales].filter(sale => filter === 'Tudo' || (filter === 'Hoje' ? new Date(sale.date).toDateString() === new Date().toDateString() : now - new Date(sale.date).getTime() <= 7 * 86400000)).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()); }, [sales, filter]);
  const total = filtered.reduce((sum, sale) => sum + sale.totalCents, 0);
  const average = filtered.length ? Math.round(total / filtered.length) : 0;

  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.container}><View style={styles.header}><View><Text style={styles.title}>Vendas</Text><Text style={styles.subtitle}>Acompanhe tudo o que foi vendido.</Text></View><View style={styles.headerIcon}><Ionicons name="receipt-outline" size={21} color={COLORS.accent} /></View></View><View style={styles.filters}>{FILTERS.map(item => <TouchableOpacity key={item} style={[styles.filter, filter === item && styles.filterActive]} onPress={() => setFilter(item)}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></TouchableOpacity>)}</View><View style={styles.summary}><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Faturamento</Text><Text style={styles.summaryValue}>{money(total)}</Text></View><View style={styles.summaryDivider} /><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Vendas</Text><Text style={styles.summaryValue}>{filtered.length}</Text></View><View style={styles.summaryDivider} /><View style={styles.summaryItem}><Text style={styles.summaryLabel}>Ticket médio</Text><Text style={styles.summaryValue}>{money(average)}</Text></View></View><FlatList data={filtered} keyExtractor={item => item.id} renderItem={({ item }) => <SaleRow sale={item} />} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} ListHeaderComponent={<Text style={styles.listTitle}>Últimas transações</Text>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="receipt-outline" size={42} color={COLORS.textMuted} /><Text style={styles.emptyTitle}>Nenhuma venda neste período</Text><Text style={styles.emptyText}>Quando você concluir uma venda, ela aparecerá aqui.</Text></View>} /></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.bg }, container: { flex: 1, paddingHorizontal: 20 }, header: { paddingTop: 16, paddingBottom: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: COLORS.text, fontSize: 27, fontWeight: '800' }, subtitle: { color: COLORS.textMuted, fontSize: 12, marginTop: 5 }, headerIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: COLORS.surfaceAlt, alignItems: 'center', justifyContent: 'center' }, filters: { flexDirection: 'row', gap: 8, marginBottom: 14 }, filter: { flex: 1, paddingVertical: 9, borderRadius: 11, alignItems: 'center', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border }, filterActive: { backgroundColor: COLORS.text, borderColor: COLORS.text }, filterText: { color: COLORS.textSub, fontSize: 12, fontWeight: '700' }, filterTextActive: { color: COLORS.white }, summary: { backgroundColor: COLORS.surface, borderRadius: 17, borderWidth: 1, borderColor: COLORS.border, paddingVertical: 14, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 22 }, summaryItem: { flex: 1, alignItems: 'center' }, summaryLabel: { color: COLORS.textMuted, fontSize: 10, marginBottom: 5 }, summaryValue: { color: COLORS.text, fontSize: 14, fontWeight: '800' }, summaryDivider: { height: 30, width: 1, backgroundColor: COLORS.border }, list: { paddingBottom: 110 }, listTitle: { color: COLORS.text, fontSize: 16, fontWeight: '800', marginBottom: 10 }, saleCard: { backgroundColor: COLORS.surface, borderRadius: 16, borderWidth: 1, borderColor: COLORS.border, padding: 12, flexDirection: 'row', gap: 10, marginBottom: 9 }, saleIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, saleInfo: { flex: 1 }, saleTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, saleName: { color: COLORS.text, fontSize: 13, fontWeight: '800', flex: 1 }, saleTotal: { color: COLORS.text, fontSize: 13, fontWeight: '800' }, saleItem: { color: COLORS.textSub, fontSize: 12, marginTop: 5 }, saleMeta: { color: COLORS.textMuted, fontSize: 10, marginTop: 5 }, empty: { alignItems: 'center', paddingTop: 65, paddingHorizontal: 20 }, emptyTitle: { color: COLORS.text, fontSize: 15, fontWeight: '800', marginTop: 13 }, emptyText: { color: COLORS.textMuted, fontSize: 12, textAlign: 'center', lineHeight: 18, marginTop: 5 },
});
